workflows:
  ios-development:
    name: iOS Development Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: .
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        BUNDLE_ID: com.example.beginflutter           # Thay bằng Bundle ID của bạn
        XCODE_SCHEME: Runner
        XCODE_WORKSPACE: Runner.xcworkspace
        CM_PROVISIONING_PROFILE: $CM_PROVISIONING_PROFILE
        CM_CERTIFICATE: $CM_CERTIFICATE
        CM_CERTIFICATE_PASSWORD: $CM_CERTIFICATE_PASSWORD
    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Install CocoaPods dependencies
        script: |
          find . -name "Podfile" -execdir pod install \;

      - name: Set up keychain
        script: |
          keychain initialize
          echo $CM_CERTIFICATE | base64 --decode > /tmp/certificate.p12
          keychain add-certificates --certificate /tmp/certificate.p12 --password "$CM_CERTIFICATE_PASSWORD"

      - name: Set up provisioning profile
        script: |
          PROFILE_PATH="$HOME/Library/MobileDevice/Provisioning Profiles/${BUNDLE_ID}.mobileprovision"
          echo $CM_PROVISIONING_PROFILE | base64 --decode > "$PROFILE_PATH"

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa
