# ios/Podfile
platform :ios, '15.0'

# CocoaPods setup
use_frameworks!
use_modular_headers!

# Thêm Flutter
# Không require trực tiếp Flutter.framework nữa

target 'Runner' do
  # Pods for Runner
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end
