# ios/Podfile
platform :ios, '15.0'

# CocoaPods dependencies
use_frameworks!
use_modular_headers!

# Thêm repo Flutter
require File.expand_path('../Flutter/Flutter.framework', __FILE__)

target 'Runner' do
  # Pods for Runner
  flutter_root = File.expand_path('../Flutter', __FILE__)
  eval(File.read(File.join(flutter_root, 'podhelper.rb')), binding)
end
